name: Waka Readme   # ← 워크플로 이름 (좌측에 표시될 이름)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  waka-stats:                        # ← 여기 job id를 고유하게 바꿔줌
    name: Update WakaTime Stats     # ← 표시될 job 이름
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
