name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # added for manual run

jobs:
  update-readme:
    name: WakaTime Readme Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
